### ISSUE TITLE
Scan issue

### ISSUE THREAD

**Issue by jaikishantulswani** [EdOverflow/smith#3]
Hello @EdOverflow 
Not able to scan more then 30 host at a time even when the file is having 100+ hosts, meanwhile the modem also hang up and have to restart the modem every time.

**Comment by jaikishantulswani** [comment]
resolved by removing "concurrency" switch :+1:

**Comment by jaikishantulswani** [comment]
Hello @EdOverflow ,
Modem become unresponsive / hang whenever scan 100+ hosts,  not resolve even after delay switch           -d 1000

**Comment by EdOverflow** [comment]
This tool is not meant to be run from your home network. I would advise to run smith from a server.

**Comment by jaikishantulswani** [comment]
So what's the prerequisite to run smith from home network ?
